# Generated by Django 5.2.7 on 2025-10-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dininghall',
            old_name='name',
            new_name='hallName',
        ),
    ]
