# Generated by Django 5.2.7 on 2025-10-25 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_rename_name_dininghall_hallname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiningHall',
            new_name='DiningHall_1',
        ),
    ]
