# Generated by Django 5.2.7 on 2025-10-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_rename_dininghall_dininghall_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallName', models.CharField(max_length=100)),
                ('hours', models.CharField(max_length=20)),
                ('mealHours', models.JSONField(blank=True, default=dict)),
                ('meals', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.DeleteModel(
            name='DiningHall_1',
        ),
    ]
