# Generated by Django 5.2.8 on 2025-12-06 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_dininghall_delete_dininghall_1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.TextField(max_length=1000)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('foodPreferences', models.JSONField(blank=True, default=list, help_text="User's preferred food types, e.g. ['vegetarian', 'halal']")),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('diningHall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='menus.dininghall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
