# Generated by Django 5.2.8 on 2025-12-06 04:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_review_updatedat_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calories', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('allergens', models.JSONField(blank=True, default=list, help_text="Allergens present, e.g. ['milk', 'gluten']")),
                ('dietTags', models.JSONField(blank=True, default=list, help_text="Diet tags, e.g. ['vegetarian', 'halal']")),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergens', models.JSONField(blank=True, default=list, help_text="Allergens to avoid, e.g. ['milk', 'eggs']")),
                ('calorieTarget', models.IntegerField(default=2000, help_text='Daily calorie target', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(5000)])),
                ('dietPreferences', models.JSONField(blank=True, default=list, help_text="Diet preferences, e.g. ['vegetarian', 'halal']")),
                ('surveyCompleted', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
