# Generated by Django 5.2.8 on 2025-12-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_mealhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dininghall',
            name='menuByDate',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
